### ISSUE TITLE
Win 10 中安装的 Jupyter 不能初始化启动页面

### ISSUE THREAD

**Issue by leiyunhe** [leiyunhe/PrecisionTeachingAndLearning#25]
>问题同这个：https://www.zhihu.com/question/56570933
# 技术环境
- 硬件：hp 一体机
- 处理器：Intel Core i5-3470 CPU 3.20GHz
- 系统类型： 64位操作系统，基于x64的处理器
- 内存： 4.00 GB
- 系统版本：Windows 10 专业版
- 软件环境：Python 3 + Sublime 2 Text / Typora + Git 

# 预想目标：安装 jupyter notebook
- ```pip install jupyter```
- ```jupyter notebook```

# 最终解决方案（见尝试二）: 通过 Anaconda 安装

>参考：[通过 Anaconda 使用 jupyter](http://blog.csdn.net/tina_ttl/article/details/53769256)

- 安装 Anaconda
- 开始菜单，搜索 Anaconda navigator
- 点击 Launch jupyter
- 结论：安装成功

# 我的尝试：

## 尝试一：重新安装 Python3 
- 报错信息如下：
```
Traceback (most recent call last):
  File "c:\python3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python3\Scripts\jupyter-notebook.EXE\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\python3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "c:\python3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python3\lib\site-packages\notebook\notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "c:\python3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python3\lib\site-packages\jupyter_core\application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "c:\python3\lib\site-packages\notebook\notebookapp.py", line 1007, in parse_command_line
    super(NotebookApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "c:\python3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\python3\lib\site-packages\traitlets\config\application.py", line 536, in parse_command_line
    flags=flags, log=self.log)
  File "c:\python3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "c:\python3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "c:\python3\lib\site-packages\traitlets\config\application.py", line 226, in _log_default
    _log_formatter = self._log_formatter_cls(fmt=self.log_format, datefmt=self.log_datefmt)
  File "c:\python3\lib\site-packages\tornado\log.py", line 154, in __init__
    raise RuntimeError("No supported color terminal library")
RuntimeError: No supported color terminal library
```
- 结论：重新安装 Python 3 环境，仍然无法打开。
## 尝试二：安装 Anaconda

>参考：[通过 Anaconda 使用 jupyter](http://blog.csdn.net/tina_ttl/article/details/53769256)

- 安装 Anaconda
- 开始菜单，搜索 Anaconda navigator
- 点击 Launch jupyter
- 结论：安装成功

**Comment by leiyunhe** [comment]
# Anaconda
- [官网下载](https://www.continuum.io/downloads#windows)
-
